#!/usr/bin/env bun
import { existsSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { resolve, join } from "node:path";
import { RUNS_DIR, TOOLS_DIR } from "../runtime/lib/paths.ts";
import { atomicWriteText } from "../runtime/lib/io.ts";
import { appendRunLog } from "../runtime/lib/log.ts";

const toolArg = process.argv[2];
if (!toolArg) {
  console.error("usage: new_run.ts tool1,tool2,tool3");
  process.exit(1);
}
const tools = toolArg.split(",").map((s) => s.trim()).filter(Boolean);
const missing = tools.filter((t) => !existsSync(join(TOOLS_DIR, t, "code.ts")));
if (missing.length > 0) {
  console.error(`unknown tools: ${missing.join(", ")}`);
  process.exit(1);
}

const stamp = new Date().toISOString().replace(/[:.]/g, "-");
const runId = stamp;
const runFile = resolve(RUNS_DIR, `${stamp}.ts`);
await mkdir(RUNS_DIR, { recursive: true });

const importLines = tools
  .map((t) => `import _${t} from "../../tools/${t}/code.ts";`)
  .join("\n");
const wrapLines = tools
  .map((t) => `const ${t} = wrapWithStats("${t}", _${t}, RUN_ID);`)
  .join("\n");

const tpl = `// AUTO-GENERATED by scripts/new_run.ts — edit INPUT and BODY blocks only.
import { wrapWithStats } from "../lib/stats-proxy.ts";
${importLines}

const RUN_ID = "${runId}";
${wrapLines}

// ─── INPUT ──────────────────────────────────────────────────
const input = {
  // CLAUDE: fill this
};
// ─── BODY ───────────────────────────────────────────────────
async function main() {
  // CLAUDE: orchestration here. Prefer Promise.all for independent calls.
  // Use console.error for debug (stdout is reserved for the JSON result).
  // Return the final object.
  return {};
}
// ─── OUTPUT ─────────────────────────────────────────────────
main()
  .then((result) => {
    process.stdout.write(JSON.stringify({ success: true, result }) + "\\n");
  })
  .catch((error) => {
    process.stdout.write(
      JSON.stringify({
        success: false,
        error: { message: error?.message ?? String(error), stack: error?.stack },
      }) + "\\n",
    );
    process.exit(1);
  });
`;

await atomicWriteText(runFile, tpl);
await appendRunLog({ phase: "scaffold", runId, tools });
console.log(JSON.stringify({ ok: true, path: runFile, runId, tools }));
